version: '2'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      .env.docker
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: .
    command: rails s -b 0.0.0.0
    volumes:
      - .:/supergirl
    ports:
      - 80:3000
      - 3000:3000
    env_file:
      .env.docker
    links:
      - db
volumes:
  postgres-data:
